"""initial_19_entities

Revision ID: fe0d749a6f17
Revises: 
Create Date: 2026-09-14 10:52:54.505287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0d749a6f17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('target_users', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_organizer', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.String(length=100), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('tech_frontend', sa.String(length=255), nullable=True),
    sa.Column('tech_backend', sa.String(length=255), nullable=True),
    sa.Column('tech_database', sa.String(length=255), nullable=True),
    sa.Column('tech_ai', sa.String(length=255), nullable=True),
    sa.Column('tech_apis', sa.String(length=255), nullable=True),
    sa.Column('tech_hosting', sa.String(length=255), nullable=True),
    sa.Column('tech_other', sa.Text(), nullable=True),
    sa.Column('feedback_goal', sa.String(length=100), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_event_name'), 'projects', ['event_name'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('ai_generations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('generation_type', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_project_id'), 'ai_generations', ['project_id'], unique=False)
    op.create_table('audit_jobs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_jobs_project_id'), 'audit_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_jobs_status'), 'audit_jobs', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('feedback_forms',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('allow_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_forms_project_id'), 'feedback_forms', ['project_id'], unique=False)
    op.create_index(op.f('ix_feedback_forms_slug'), 'feedback_forms', ['slug'], unique=True)
    op.create_table('project_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_links_project_id'), 'project_links', ['project_id'], unique=False)
    op.create_table('audit_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=False),
    sa.Column('ux_score', sa.Integer(), nullable=False),
    sa.Column('a11y_score', sa.Integer(), nullable=False),
    sa.Column('perf_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['audit_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_project_id'), 'audit_runs', ['project_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_form_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_feedback_form_id'), 'campaigns', ['feedback_form_id'], unique=False)
    op.create_index(op.f('ix_campaigns_project_id'), 'campaigns', ['project_id'], unique=False)
    op.create_table('feedback_responses',
    sa.Column('feedback_form_id', sa.Uuid(), nullable=False),
    sa.Column('respondent_name', sa.String(length=255), nullable=True),
    sa.Column('respondent_email', sa.String(length=255), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_responses_feedback_form_id'), 'feedback_responses', ['feedback_form_id'], unique=False)
    op.create_table('feedback_sections',
    sa.Column('feedback_form_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_sections_feedback_form_id'), 'feedback_sections', ['feedback_form_id'], unique=False)
    op.create_table('feedback_themes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_form_id', sa.Uuid(), nullable=False),
    sa.Column('theme_title', sa.String(length=255), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_themes_feedback_form_id'), 'feedback_themes', ['feedback_form_id'], unique=False)
    op.create_index(op.f('ix_feedback_themes_project_id'), 'feedback_themes', ['project_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('audit_run_id', sa.Uuid(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('sentiment_distribution', sa.JSON(), nullable=False),
    sa.Column('positive_themes', sa.JSON(), nullable=True),
    sa.Column('negative_themes', sa.JSON(), nullable=True),
    sa.Column('feature_requests', sa.JSON(), nullable=True),
    sa.Column('common_complaints', sa.JSON(), nullable=True),
    sa.Column('most_praised', sa.JSON(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('is_sample_size_limited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_project_id'), 'ai_analysis', ['project_id'], unique=False)
    op.create_table('audit_findings',
    sa.Column('audit_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('affected_url', sa.Text(), nullable=False),
    sa.Column('recommended_fix', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_audit_run_id'), 'audit_findings', ['audit_run_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_project_id'), 'audit_findings', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_severity'), 'audit_findings', ['severity'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_table('feedback_questions',
    sa.Column('feedback_form_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('min_label', sa.String(length=100), nullable=True),
    sa.Column('max_label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['feedback_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_questions_feedback_form_id'), 'feedback_questions', ['feedback_form_id'], unique=False)
    op.create_table('audit_evidence',
    sa.Column('audit_finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audit_finding_id'], ['audit_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_evidence_audit_finding_id'), 'audit_evidence', ['audit_finding_id'], unique=False)
    op.create_table('feedback_options',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['feedback_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_options_question_id'), 'feedback_options', ['question_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('audit_finding_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('remediation_steps', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('correlated_feedback_count', sa.Integer(), nullable=False),
    sa.Column('ease_of_fixing', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_finding_id'], ['audit_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_project_id'), 'recommendations', ['project_id'], unique=False)
    op.create_table('response_answers',
    sa.Column('feedback_response_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('selected_options', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_response_id'], ['feedback_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['feedback_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_answers_feedback_response_id'), 'response_answers', ['feedback_response_id'], unique=False)
    op.create_index(op.f('ix_response_answers_question_id'), 'response_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_answers_question_id'), table_name='response_answers')
    op.drop_index(op.f('ix_response_answers_feedback_response_id'), table_name='response_answers')
    op.drop_table('response_answers')
    op.drop_index(op.f('ix_recommendations_project_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_feedback_options_question_id'), table_name='feedback_options')
    op.drop_table('feedback_options')
    op.drop_index(op.f('ix_audit_evidence_audit_finding_id'), table_name='audit_evidence')
    op.drop_table('audit_evidence')
    op.drop_index(op.f('ix_feedback_questions_feedback_form_id'), table_name='feedback_questions')
    op.drop_table('feedback_questions')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_audit_findings_severity'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_project_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_audit_run_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index(op.f('ix_ai_analysis_project_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_feedback_themes_project_id'), table_name='feedback_themes')
    op.drop_index(op.f('ix_feedback_themes_feedback_form_id'), table_name='feedback_themes')
    op.drop_table('feedback_themes')
    op.drop_index(op.f('ix_feedback_sections_feedback_form_id'), table_name='feedback_sections')
    op.drop_table('feedback_sections')
    op.drop_index(op.f('ix_feedback_responses_feedback_form_id'), table_name='feedback_responses')
    op.drop_table('feedback_responses')
    op.drop_index(op.f('ix_campaigns_project_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_feedback_form_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_runs_project_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_project_links_project_id'), table_name='project_links')
    op.drop_table('project_links')
    op.drop_index(op.f('ix_feedback_forms_slug'), table_name='feedback_forms')
    op.drop_index(op.f('ix_feedback_forms_project_id'), table_name='feedback_forms')
    op.drop_table('feedback_forms')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_audit_jobs_status'), table_name='audit_jobs')
    op.drop_index(op.f('ix_audit_jobs_project_id'), table_name='audit_jobs')
    op.drop_table('audit_jobs')
    op.drop_index(op.f('ix_ai_generations_project_id'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_event_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
